---
title: "Long wait projections"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}

current_position <- current_position %>% 
  filter(est_position_at_deadline > 0) %>% 
  filter(organisation_name == t)

admitted_projections <- current_position %>% 
  filter(wait_type == 'DTA_Wait') %>% 
  select(tfc_name, 
         current_ptl,
         current_long_waits,
         est_position_at_deadline,
         change_trend) %>% 
  arrange(desc(est_position_at_deadline))

op_projections <- current_position %>% 
  filter(wait_type == 'OP_Wait')%>% 
  select(tfc_name,
         current_ptl,
         current_long_waits,
         est_position_at_deadline,
         change_trend) %>% 
  arrange(desc(est_position_at_deadline))

total_dta_specs <-  specs_per_org %>% 
  filter(organisation_name == t &
           wait_type=='DTA_Wait') %>% 
  pull(total_specs)

total_op_specs <-  specs_per_org %>% 
  filter(organisation_name == t &
           wait_type=='OP_Wait') %>% 
  pull(total_specs)

dta_breach_specs <- nrow(admitted_projections)
op_breach_specs <- nrow(op_projections)

```

OUH {data-navmenu="BOB"}
====================================== 

Column {data-width=700}
-----------------------------------------------------------------------

### Admitted specialities - projected breaches

```{r admitted projections}
datatable(admitted_projections,
          class = 'cell-border stripe',
          colnames = c('Treatment Function',
                       'Current PTL',
                       'Current Long Waits',
                       'Est. Position At Deadline',
                       'Change Trend'),
          rownames = FALSE) %>% 
          formatStyle('change_trend',
                      backgroundColor = styleEqual(c('growing','no change','reducing'),
                                                   c(table_red,highlight,table_green)),
                      color = 'white')
```

### Non-Admitted specialities - projected breaches

```{r outpatient projections}
datatable(op_projections,
          class = 'cell-border stripe',
          colnames = c('Treatment Function',
                       'Current PTL',
                       'Current Long Waits',
                       'Est. Position At Deadline',
                       'Change Trend'),
          rownames = FALSE) %>% 
          formatStyle('change_trend',
                      backgroundColor = styleEqual(c('growing','no change','reducing'),
                                                   c(table_red,highlight,table_green)),
                      color = 'white')

```

Column {data-width=300}
-----------------------------------------------------------------------

### Percentage of admitted specialities with projected long waits after deadline 

```{r valuebox showing % of admitted specialities with projected breaches}

valueBox(round(dta_breach_specs/total_dta_specs*100,1), icon = 'fa-percent')

```

### admitted long waits by week 

``` {r }
apc_lw_trend <- full_long_wait_data %>% 
  filter(organisation_name == t & wait_type == 'DTA_Wait') %>% 
  select(week_ending,
         long_waits_cleaned) %>% 
  group_by(week_ending) %>% 
  mutate(long_waits = sum(long_waits_cleaned)) %>% 
  ungroup()

apc_lw_trend <- ggplot(apc_lw_trend, aes(x=week_ending,y=long_waits))+
  geom_point()+
  expand_limits(y=0)+
  #scale_x_date(breaks = 'week')+
  theme(axis.text.x = element_text(angle = 30))

ggplotly(apc_lw_trend)


```


### Percentage of non-admitted specialities with projected long waits after deadline 

```{r valuebox showing % of non-admitted specialities with projected breaches}

valueBox(round(op_breach_specs/total_op_specs*100,1), icon = 'fa-percent')

```

### outpatient long waits by week

``` {r }
op_lw_trend <- full_long_wait_data %>% 
  filter(organisation_name == t & wait_type == 'OP_Wait') %>% 
  select(week_ending,
         long_waits_cleaned) %>% 
  group_by(week_ending) %>% 
  mutate(long_waits = sum(long_waits_cleaned)) %>% 
  ungroup() 

op_lw_trend <- ggplot(op_lw_trend, aes(x=week_ending,y=long_waits))+
  geom_point()+
  expand_limits(y=0)+
  #scale_x_date(breaks = 'week')+
  theme(axis.text.x = element_text(angle = 30))

ggplotly(op_lw_trend)
```






