---
title: "Long wait projections"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}

current_position <- current_position %>% 
  filter(est_position_at_deadline > 0) %>% 
  filter(organisation_name == t)

admitted_projections <- current_position %>% 
  filter(wait_type == 'DTA_Wait') %>% 
  select(organisation_name,
         tfc_name, 
         current_ptl,
         current_long_waits,
         est_position_at_deadline,
         change_trend) %>% 
  arrange(desc(est_position_at_deadline))

op_projections <- current_position %>% 
  filter(wait_type == 'OP_Wait')%>% 
  select(organisation_name,
         tfc_name,
         current_ptl,
         current_long_waits,
         est_position_at_deadline,
         change_trend) %>% 
  arrange(desc(est_position_at_deadline))

```
# Page 1 
Column {data-width=850}
-----------------------------------------------------------------------

### Admitted specialities - projected breaches

```{r admitted projections}
datatable(admitted_projections,
          class = 'cell-border stripe',
          colnames = c('Provider Name',
                       'Treatment Function',
                       'Current PTL',
                       'Current Long Waits',
                       'Est. Position At Deadline',
                       'Change Trend'),
          rownames = FALSE) %>% 
          formatStyle('change_trend',
                      backgroundColor = styleEqual(c('growing','no change','reducing'),
                                                   c(table_red,highlight,table_green)),
                      color = 'white')

```

### Non-Admitted specialities - projected breaches

```{r outpatient projections}
datatable(op_projections,
          class = 'cell-border stripe',
          colnames = c('Provider Name',
                       'Treatment Function',
                       'Current PTL',
                       'Current Long Waits',
                       'Est. Position At Deadline',
                       'Change Trend'),
          rownames = FALSE) %>% 
          formatStyle('change_trend',
                      backgroundColor = styleEqual(c('growing','no change','reducing'),
                                                   c(table_red,highlight,table_green)),
                      color = 'white')

```

Column {data-width=150}
-----------------------------------------------------------------------

### Chart B

```{r gague showing % of admitted specialities with projected breaches}

```

### Chart C

```{r gague showing % of non-admitted specialities with projected breaches}

```

# Page 2 

## Column {data-width=1000}

