---
title: Long wait projections - test
author: "John Cusack"
date: "2023-06-22"
output: html_document
sansfont: Calibri   

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, echo = FALSE)


#if(paramicb != region_name){
#  param_current_position <- current_position %>% filter(stp_name == paramicb)
#} else {
#  param_current_position <- current_position
#  }
#
#system_name <- if(paramicb != region_name){
#  system_name <- paramicb 
#  system_name <- str_replace(str_to_title(system_name),'Nhs','NHS')
#} else {
#  system_name <- region_name
#} 

```

## Purpose and methodology of this document

Some words about what the report does

## Current position {.tabset .tabset-pills}

``` {r predicted deadline breaches, results='asis'}

icbs <- current_position %>% 
  distinct(stp_name) %>% 
  pull(stp_name)

current_position <- current_position %>% 
  filter(est_position_at_deadline > 0)

for (i in icbs) {
  cat("###", i, '<br>', '\n')
trust_list <- current_position %>% 
  filter(stp_name == i) %>% 
  distinct(organisation_name) %>% 
  pull(organisation_name)

for (t in trust_list) {
    cat("####", t, '<br>', '\n')
    admitted_projections <- current_position %>% 
      filter(wait_type == 'DTA_Wait',
             organisation_name == t) %>% 
      select(tfc_name,
             current_ptl,
             current_long_waits,
             est_position_at_deadline,
             change_trend) %>% 
      arrange(desc(est_position_at_deadline))

    op_projections <- current_position %>% 
      filter(wait_type == 'OP_Wait',
             organisation_name == t)%>% 
      select(tfc_name,
             current_ptl,
             current_long_waits,
             est_position_at_deadline,
             change_trend) %>% 
      arrange(desc(est_position_at_deadline))
    
  if (nrow(admitted_projections>0)) { 
  kbl(admitted_projections,
        caption = 'Admitted Waiting List',
        col.names = c('Treatment Function',
                     'Current Total PTL',
                     'Current Long Waits',
                     'Est Position At Deadline',
                     'Change Trend')) %>% 
      kable_styling(bootstrap_options = 'striped',
                      font_size = 12,
                      full_width = FALSE) %>% 
      column_spec(5,background=case_when(admitted_projections$change_trend == 'growing' ~ table_red,
                                         admitted_projections$change_trend == 'no change' ~ highlight,
                                         admitted_projections$change_trend == 'reducing' ~ table_green),
                  color = 'white') %>% 
    cat}
    
  if (nrow(op_projections>0)) { 
  kbl(op_projections,
        caption = 'Non-admitted Waiting List',
        col.names = c('Treatment Function',
                     'Current Total PTL',
                     'Current Long Waits',
                     'Est Position At Deadline',
                     'Change Trend')) %>% 
      kable_styling(bootstrap_options = 'striped',
                      font_size = 12,
                      full_width = FALSE) %>% 
      column_spec(5,background=case_when(op_projections$change_trend == 'growing' ~ table_red,
                                        op_projections$change_trend == 'no change' ~ highlight,
                                        op_projections$change_trend == 'reducing' ~ table_green),
                  color = 'white') %>% 
    cat}
  cat('\n', '<br>', '\n\n')
}
  cat('\n', '<br>', '\n\n')
}

```